name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Format check
        run: black --check src tests
      - name: Lint
        run: flake8 src tests
      - name: Type check
        run: mypy src
      - name: Security check
        run: bandit -r src -q
      - name: Test
        run: pytest --cov=src --cov-report=term-missing
